name: pachpach
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  syncfusion_flutter_calendar: ^19.2.62
  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0

flutter:
  assets:
    - assets/appLogo.png

  uses-material-design: true
