// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABB2a6Ki0WgsT6sSpVIiaciGtcFELgQb0',
    appId: '1:783199010160:web:ef9acb4407dc60d0c8a3b5',
    messagingSenderId: '783199010160',
    projectId: 'pach-app-e1c1a',
    authDomain: 'pach-app-e1c1a.firebaseapp.com',
    storageBucket: 'pach-app-e1c1a.appspot.com',
    measurementId: 'G-E0J8W8CT7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcBdkqXm6iarl3iC9X8nYMt5i1CfY9otk',
    appId: '1:783199010160:android:c94551715473c933c8a3b5',
    messagingSenderId: '783199010160',
    projectId: 'pach-app-e1c1a',
    storageBucket: 'pach-app-e1c1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqbRQpyXETi6-4dBEbPnW5PQrwCDzerSE',
    appId: '1:783199010160:ios:46488bb63de0e8cfc8a3b5',
    messagingSenderId: '783199010160',
    projectId: 'pach-app-e1c1a',
    storageBucket: 'pach-app-e1c1a.appspot.com',
    iosClientId: '783199010160-463mtgmcbuct2t9cfoklef1oookdq2pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.pachpach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqbRQpyXETi6-4dBEbPnW5PQrwCDzerSE',
    appId: '1:783199010160:ios:46488bb63de0e8cfc8a3b5',
    messagingSenderId: '783199010160',
    projectId: 'pach-app-e1c1a',
    storageBucket: 'pach-app-e1c1a.appspot.com',
    iosClientId: '783199010160-463mtgmcbuct2t9cfoklef1oookdq2pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.pachpach',
  );
}
